spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/18679658563/silenceDemo.git
          searchPaths: config/src/main/resources/properties
        username: m18679658563@163.com
        password: txw19940603
server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

